# Generated by Django 2.1.5 on 2019-01-22 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smob', models.IntegerField(max_length=11)),
                ('rmob', models.IntegerField(max_length=11)),
                ('tdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(max_length=100000)),
                ('balance', models.IntegerField(max_length=1000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
