# Generated by Django 2.1.5 on 2019-01-22 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_auto_20190122_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions_log',
            new_name='TransactionsLog',
        ),
    ]
